import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './i18n'
import App from './App.tsx'
import { initSentry } from './sentry'
import { ErrorBoundary } from './components/ErrorBoundary'

initSentry()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </StrictMode>,
)

// Register the service worker generated by vite-plugin-pwa.
// TODO(push): the generated SW has no `push` event handler yet because
// vite-plugin-pwa in `generateSW` mode does not expose a clean hook for
// injecting one. The subscribe flow in Home.tsx is wired end-to-end, but
// delivered notifications will be ignored by the client until we either
// switch this registration to `injectManifest` with a custom SW or inject
// the handler via a Workbox plugin. Tracked for a follow-up.
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  void import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({ immediate: true })
  })
}
